zabbix_export:
  version: '7.0'
  host_groups:
    - uuid: 1f8c05f2e0bf4a699b24bf0da2b80cd9
      name: Sys-AIMS
    - uuid: 4959189ef1a042f49b5d35170ce8856b
      name: Sys-AIMS/A
    - uuid: ef4030645e2c4a37a70ead85a06e0819
      name: Sys-AIMS/B
  hosts:
    - host: A-pitwall_api
      name: A-pitwall_api
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS/A
      tags:
        - tag: company
          value: A
        - tag: role
          value: dependency
      macros:
        - macro: '{$HEALING.MODE}'
          value: 'off'
        - macro: '{$SERVICE.URL}'
          value: 'http://172.31.9.142:8081/status.json'
      inventory_mode: DISABLED
    - host: A-pitwall_web
      name: A-pitwall_web
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS/A
      tags:
        - tag: company
          value: A
        - tag: container
          value: pitwall_web
      macros:
        - macro: '{$HEALING.MODE}'
          value: auto
        - macro: '{$SERVICE.URL}'
          value: 'http://172.31.9.142/healthz'
      inventory_mode: DISABLED
    - host: B-pitwall_api
      name: B-pitwall_api
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS/B
      tags:
        - tag: company
          value: B
        - tag: role
          value: dependency
      macros:
        - macro: '{$HEALING.MODE}'
          value: 'off'
        - macro: '{$SERVICE.URL}'
          value: 'http://172.31.9.33:8081/status.json'
      inventory_mode: DISABLED
    - host: B-pitwall_web
      name: B-pitwall_web
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS/B
      tags:
        - tag: company
          value: B
        - tag: container
          value: pitwall_web
      macros:
        - macro: '{$HEALING.MODE}'
          value: auto
        - macro: '{$SERVICE.URL}'
          value: 'http://172.31.9.33/healthz'
      inventory_mode: DISABLED
    - host: healer
      name: healer
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS
      tags:
        - tag: company
          value: internal
        - tag: role
          value: automation
      macros:
        - macro: '{$HEALING.MODE}'
          value: 'off'
        - macro: '{$SERVICE.URL}'
          value: 'http://healer:8080/health'
      inventory_mode: DISABLED
    - host: pitwall_api
      name: pitwall_api
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS
      tags:
        - tag: company
          value: internal
        - tag: role
          value: dependency
      macros:
        - macro: '{$HEALING.MODE}'
          value: 'off'
        - macro: '{$SERVICE.URL}'
          value: 'http://pitwall_api/status.json'
      inventory_mode: DISABLED
    - host: pitwall_web
      name: pitwall_web
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS
      tags:
        - tag: company
          value: internal
        - tag: container
          value: pitwall_web
      macros:
        - macro: '{$SERVICE.URL}'
          value: 'http://pitwall_web/healthz'
      inventory_mode: DISABLED
    - host: rca
      name: rca
      templates:
        - name: 'Sys-AIMS HTTP Service'
      groups:
        - name: Sys-AIMS
      tags:
        - tag: company
          value: internal
        - tag: role
          value: automation
      macros:
        - macro: '{$HEALING.MODE}'
          value: 'off'
        - macro: '{$SERVICE.URL}'
          value: 'http://rca:8081/health'
      inventory_mode: DISABLED
    - host: vm-a-os
      name: vm-a-os
      templates:
        - name: 'Linux by Zabbix agent active'
      groups:
        - name: Sys-AIMS/A
      tags:
        - tag: company
          value: A
        - tag: role
          value: host-os
      macros:
        - macro: '{$HEALING.MODE}'
          value: 'off'
      inventory_mode: DISABLED
    - host: vm-b-os
      name: vm-b-os
      templates:
        - name: 'Linux by Zabbix agent active'
      groups:
        - name: Sys-AIMS/B
      tags:
        - tag: company
          value: B
        - tag: role
          value: host-os
      macros:
        - macro: '{$HEALING.MODE}'
          value: 'off'
      inventory_mode: DISABLED
    - host: zabbix-agent
      name: zabbix-agent
      templates:
        - name: 'Linux by Zabbix agent'
      groups:
        - name: Sys-AIMS
      interfaces:
        - useip: 'NO'
          ip: ''
          dns: zabbix-agent
          interface_ref: if1
      tags:
        - tag: company
          value: internal
        - tag: role
          value: host-os
      inventory_mode: DISABLED
